---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: HALLO
headerStyle: clean
favicon: /images/runes.png?v=4
background: https://images.unsplash.com/photo-1672288072591-619afe830096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80
backgroundOpacity: 0.5
layout:
    header:
        style: column
        rows: 2
	
